server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/fjmgithub/spring-cloud-config.git #GitHub上面的git仓库名字
          uri: git@github.com:fjmgithub/spring-cloud-config.git #GitHub上面的git仓库名字
          ####搜索目录
#          search-paths:
#            - spring-cloud-config
          skip-ssl-validation: true
          username: fjmgithub
          password: fjm@github.com1
          force-pull: true
      ####读取分支
      label: main

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
